export * as AddressG5Model from './addressG5.model';
export * as SpecialistG6Model from './specialistG6.model';
export * as UserSpecialtyG1Model from './userSpecialtyG1.model';
export * as UserModel from './userG2.model';
export * as SpecialtyModel from './specialty.model';
export * as UserInfo from './userG2.model';
export * as UserG8Model from './userG8.model';
export * as AddressModel from './address.model';
export * as UserG1Model from './userG1.model';
